discord: 
  uri: discord
  dir: oauth2
skins: 
  uri: skins
  dir: skins
mail: 
  uri: mail
  dir: mail
system:
  uri: system
  dir: system
discordacc: 
  uri: discordacc
  dir: discordacc
gml: 
  uri: gml
  dir: gml