# This file is part of CookieCMS Open.
#
# CookieCMS Open is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CookieCMS Open is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with CookieCMS Open. If not, see <http://www.gnu.org/licenses/>.
basic:
  registerTypes:
    basic: true
    discord: true
    mail: true
  registration: true
  # if mail on, it will require account verification
  requiredVerify: false
  ssl: true
  domain: "CookieCMS Open.coffeedev.dev"
  # version: company/club
  version: club
  BlockLocalhost: true
  AccountsPerIP : 1
  skindefault: 
    skin: ""
    slim: false 
logs:
  accounts:
    token: "https://discord.com/api/webhooks/1209533104952447056/jgKS1cU8PsR24ac_6z9l_q7JiTSmhH3qXSKNG8VO1UPTn3Tml2QVTLx5SOfWbObRSHN5"
    createacc: 0

# maintenance section
maintenance:
  enabled: false
  comment: ""
  unixstemp: ""

# database section
database:
  host: "127.0.0.1"
  username: "root"
  pass: ""
  db: "cmscookie"
  port: "3306"

# smtp section
smtp:
  host: ""
  SMTPAuth: true
  Username: ""
  Password: ""
  SMTPSecure: ""
  Port: 587

# debug section
debug:
  debug: false
  development: false
  generatorusername: false
  outLogMasterFasterErrorOutPut: false

# discord section
discord:
  enabled: true
  client_id: "1181148727826722816"
  secret_id: ""
  scopes: "identify"
  redirect_url: "http://CookieCMS Open.local/api/discord"
  bot: ""
  guild_id: 0
  role: 0
  webhooks: ""

# antifake section
antifake:
  allowregister: false
  webhookdiscord: ""
