basic:
  registerTypes:
    basic: true
    discord: true
    mail: true
  registration: true
  # if mail on, it will require account verification
  requiredVerify: false
  ssl: true
  domain: "cookiecms.coffeedev.dev"
  # version: company/club
  version: club
  blocklocalhost: false
  accountperip : 1
  skindefault: 
    skin: ""
    slim: false 
logs:
  accounts:
    token: "https://discord.com/api/webhooks/1209533104952447056/jgKS1cU8PsR24ac_6z9l_q7JiTSmhH3qXSKNG8VO1UPTn3Tml2QVTLx5SOfWbObRSHN5"
    createacc: 0

# maintenance section
maintenance:
  enabled: true
  comment: ""
  unixstemp: ""

# database section
database:
  host: "127.0.0.1"
  username: "root"
  pass: ""
  db: "cmscookie"
  port: "3306"

# smtp section
smtp:
  host: "smtppro.zoho.eu"
  SMTPAuth: true
  Username: "noreply@coffeedev.dev"
  Password: "r%nytuD2"
  SMTPSecure: ""
  Port: 587

# debug section
debug:
  debug: true
  development: false
  generatorusername: false
  outLogMasterFasterErrorOutPut: false

# discord section
discord:
  enabled: true
  client_id: "1181148727826722816"
  secret_id: "5YaScJyKq0pDQxO_B5YlhUwcBnlkr37P"
  scopes: "identify"
  redirect_url: "http://cookiecms.local/api/discord"
  bot: ""
  guild_id: 0
  role: 0
  webhooks: ""

# antifake section
antifake:
  allowregister: false
  webhookdiscord: ""
