# This file is part of CookieCMS Open.
#
# CookieCMS Open is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CookieCMS Open is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with CookieCMS Open. If not, see <http://www.gnu.org/licenses/>.
home:
  uri: home
  maintenance: true
  template: home
  variablesPath : home
  default: ""
  category: false
admin:
  uri: admin
  maintenance: false
  template: admin
  variablesPath : admin
  default: index
  category: true
index:
  uri: index
  maintenance: true
  template: index
  variablesPath : index
  default: "1"
  category: false
settings:
  uri: settings
  maintenance: false
  template: settings
  variablesPath : settings
  default: "settings"
  auto: false
  category: false
auth:
  uri: auth
  maintenance: false
  template: auth
  variablesPath : auth
  default: "login"
  category: true
