home:
  uri: home
  maintenance: true
  template: home
  variablesPath : home
  default: ""
  category: false
admin:
  uri: admin
  maintenance: false
  template: admin
  variablesPath : admin
  default: index
  category: true
index:
  uri: index
  maintenance: true
  template: index
  variablesPath : index
  default: "1"
  category: false
settings:
  uri: settings
  maintenance: false
  template: settings
  variablesPath : settings
  default: "settings"
  auto: false
  category: false
