home:
  uri: home
  maintenance: false
  template: home
  variablesPath : home
admin:
  uri: admin
  maintenance: false
  template: 
  variablesPath : admin
  suffix: 
    enabled: true
index:
  uri: index
  maintenance: true
  template: index
  variablesPath : index