home:
  uri: home
  maintenance: false
  template: home
  variablesPath : home
  default: ""
admin:
  uri: admin
  maintenance: false
  template: admin
  variablesPath : admin
  suffix: 
    enabled: true
  default: index
index:
  uri: index
  maintenance: true
  template: index
  variablesPath : index
  default: "1"