projectname: "Cookie cms"
icon: "assets/cookie.png"
bootstrapcss: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
bootstrapjs: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
bootstrapicons: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
jquery: "https://code.jquery.com/jquery-3.6.0.min.js"
indexdescription: "Minecraft project with launcher x)"
navvbarpic: "discord"
snow: false
